### ISSUE TITLE
Error While Installing PhpBolt Can You Please Suggest a solution

### ISSUE THREAD

**Issue by MhmdAsq** [SiavashBamshadnia/Laravel-Source-Encrypter#10]
Problem 1
    - Installation request for sbamtr/laravel-source-encrypter ^1.2 -> satisfiable by sbamtr/laravel-source-encrypter[1.2.0].
    - sbamtr/laravel-source-encrypter 1.2.0 requires ext-bolt * -> the requested PHP extension bolt is missing from your system.

  To enable extensions, verify that they are enabled in your .ini files:
    - C:\xampp\php\php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

![image](https://user-images.githubusercontent.com/62282076/99444061-b0c14000-2941-11eb-9d0b-31165f4516df.png)

**Comment by SiavashBamshadnia** [comment]
You have to install phpbolt extension first.
See this:
https://phpbolt.com/download-phpbolt

**Comment by MhmdAsq** [comment]
I have installed it but still, the problem comes

**Comment by SiavashBamshadnia** [comment]
change `bolt` to `php_bolt`

**Comment by MhmdAsq** [comment]
Tried but still the same

**Comment by SiavashBamshadnia** [comment]
You have to restart your webserver
