### ISSUE TITLE
Can the files be decrypted?

### ISSUE THREAD

**Issue by hernandoglobal** [SiavashBamshadnia/Laravel-Source-Encrypter#14]
If I only have the files encrypted.
How can I decrypt the files? and see the code.

**Comment by SiavashBamshadnia** [comment]
No. You can't see the code of encrypted files.

**Comment by hernandoglobal** [comment]
Sure, but how do I decrypt.

**Comment by SiavashBamshadnia** [comment]
You cant see the code. The `bolt_decrypt` function runs the encrypted source code.
