### ISSUE TITLE
Blade file is not descrypted

### ISSUE THREAD

**Issue by vishalmicrolevel** [SiavashBamshadnia/Laravel-Source-Encrypter#21]
Laravel PHP file is decrypted but Laravel blade file is not decrypted it's display same to same.
Can you help me guys

**Comment by SiavashBamshadnia** [comment]
Hello. Blade files are not encrypted because they are not real PHP files.

**Comment by vishalmicrolevel** [comment]
If i want to encrypted that also then what we have to do?
