### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by SiavashBamshadnia** [SiavashBamshadnia/Laravel-Source-Encrypter#22]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires sbamtr/laravel-source-encrypter ^1.4 -> satisfiable by sbamtr/laravel-source-encrypter[1.4.0].
    - sbamtr/laravel-source-encrypter 1.4.0 requires illuminate/console ^6|^7|^8|^9 -> found illuminate/console[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.
0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev] but these were not loaded, likely because it conflicts with another require.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require sbamtr/laravel-source-encrypter:*" to figure out if any 
version is installable, or "composer require sbamtr/laravel-source-encrypter:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

_Originally posted by @aashishtimalsina in https://github.com/SiavashBamshadnia/Laravel-Source-Encrypter/issues/7#issuecomment-1237686972_

**Comment by SiavashBamshadnia** [comment]
Hi. Please see this link:

https://stackoverflow.com/questions/29318709/how-can-i-resolve-your-requirements-could-not-be-resolved-to-an-installable-set

**Comment by hanifhefaz** [comment]
@SiavashBamshadnia It doesn't work for me please show the correct way if you can. the solutions in above link don't work for me.

**Comment by SiavashBamshadnia** [comment]
Please upload your `composer.json` file here.

**Comment by hanifhefaz** [comment]
ok. so the solution is if you put the exact version in the composer.json, then it works.
