### ISSUE TITLE
ERROR  Command "encrypt-source" is not defined.

### ISSUE THREAD

**Issue by hanifhefaz** [SiavashBamshadnia/Laravel-Source-Encrypter#26]
I have downloaded phpBolt, and placed the required extension in php.ini file, but when I run php artisan encrypt-source, it shows me this error:

```
`PHP Warning:  PHP Startup: Unable to load dynamic library '/home/hanif/Downloads/phpBolt-extension-1.0.3/phpBolt-extension-1.0.3/linux 64/linux 64-php8.1' (tried: /home/hanif/Downloads/phpBolt-extension-1.0.3/phpBolt-extension-1.0.3/linux 64/linux 64-php8.1 (/home/hanif/Downloads/phpBolt-extension-1.0.3/phpBolt-extension-1.0.3/linux 64/linux 64-php8.1: cannot read file data: Is a directory), /usr/lib/php/20210902//home/hanif/Downloads/phpBolt-extension-1.0.3/phpBolt-extension-1.0.3/linux 64/linux 64-php8.1.so (/usr/lib/php/20210902//home/hanif/Downloads/phpBolt-extension-1.0.3/phpBolt-extension-1.0.3/linux 64/linux 64-php8.1.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

   ERROR  Command "encrypt-source" is not defined.`
```

I have already restarted my apache2

I can't see the service provider in my config/app.php. I am using php8.1

**Comment by SiavashBamshadnia** [comment]
You have to install this package to be able to run the `encrypt source` command. Follow this instruction:
https://github.com/SiavashBamshadnia/Laravel-Source-Encrypter#installation

**Comment by hanifhefaz** [comment]
Yes, I have already installed your package. The problem was that I just copied the path to the Bold.so file and did not include the bold.so itself at the end of extension in php.ini 

It is solved now.
