### ISSUE TITLE
Where do I set or see my encryption key?

### ISSUE THREAD

**Issue by hanifhefaz** [SiavashBamshadnia/Laravel-Source-Encrypter#27]

**Comment by SiavashBamshadnia** [comment]
The encryption key for each file is different. You can see them on the second line of encrypted-PHP files.
![Screenshot (64)](https://user-images.githubusercontent.com/3998368/201586219-8eb3ea03-ecbe-4b93-b727-8a45eab009b5.png)

**Comment by hanifhefaz** [comment]
So, when I deliver the code to the customer, he will see the key as well? will he be able to decrypt it back? Or someone who finds the code, can decrypt it back?

**Comment by SiavashBamshadnia** [comment]
No. There is no way to decrypt the source code. The only one who will have the source code is you.

**Comment by MianAsif-Riphah** [comment]
is there any chance of crash or can it effect my production environment in future? after some years like 5 or 10 years

**Comment by SiavashBamshadnia** [comment]
I'm not sure but I don't think so.
