### ISSUE TITLE
This did not work

### ISSUE THREAD

**Issue by alihastam** [SiavashBamshadnia/Laravel-Source-Encrypter#5]
laravel 7
php 7

I installed  and tested it. Encoded but it did not work with php artisan serve command on port 8000

**Comment by SiavashBamshadnia** [comment]
What error message did you get?

**Comment by alihastam** [comment]
my config is 
```
return [
    'source'      => ['app', 'database', 'routes','resources'], // Path(s) to encrypt
    'destination' => 'encrypted', // Destination path
    'key_length'  => 6, // Encryption key length
];
```
![2020-07-18_004822](https://user-images.githubusercontent.com/36451636/87828112-80816c00-c891-11ea-9aa4-cfc913cc46bb.jpg)
![2020-07-18_005300](https://user-images.githubusercontent.com/36451636/87828126-87a87a00-c891-11ea-8156-e528f0909ec4.jpg)

![2020-07-18_005927](https://user-images.githubusercontent.com/36451636/87828498-4a90b780-c892-11ea-945a-0d83ee57c097.jpg)
![2020-07-18_005910](https://user-images.githubusercontent.com/36451636/87828507-50869880-c892-11ea-99dc-a646d1606181.jpg)

**Comment by SiavashBamshadnia** [comment]
The blade templates are in resources directory and Laravel's blade templates are not real PHP codes. So PHPBolt can't encrypt these files.

**Comment by alihastam** [comment]
i test it with original views and i got error again.

**Comment by SiavashBamshadnia** [comment]
Laravel's blade templates are not PHP codes.
