### ISSUE TITLE
Error after moving project to another PC or uploading to server

### ISSUE THREAD

**Issue by halatef** [SiavashBamshadnia/Laravel-Source-Encrypter#9]
First: thanks for that great tool :+1: 
Second: 
I encrypted a laravel project and it was working good in my PC, but after uploading to the server i got the following error 

`Fatal error: Uncaught Error: Call to undefined function bolt_decrypt() in xxxxxx/app/Http/Kernel.php:2 Stack trace: #0 xxxxxx/vendor/composer/ClassLoader.php(444): include() #1 xxxxxx/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/home/stsgulf/p...') #2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Http\\Kernel') #3 [internal function]: spl_autoload_call('App\\Http\\Kernel') #4 xxxxxx/vendor/laravel/framework/src/Illuminate/Container/Container.php(752): ReflectionClass->__construct('App\\Http\\Kernel') #5 xxxxxx/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\Container\Container->build('App\\Http\\Kernel') #6 xxxxxx/vendor/laravel/framework/src/Illuminate/Container/Container.php(586): Illuminate\Container\Container->resolve('App\\Http\\Kernel', in xxxxxx/app/Http/Kernel.php on line 2`

I tried to move it to another PC i got the same error

Note: I also added the bolt extension to the new PC

**Comment by SiavashBamshadnia** [comment]
First: You're welcome :)
Second:
I think bolt extension did not installed correctly. Download and install the bolt extension in the link bellow:
https://phpbolt.com/download-phpbolt
